version: "3.6"


services:
  bot:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 6060:6060
    command: >
      sh -c "cp -rfu /cache/node_modules/. /app/node_modules/
      && npm run start"
